---
- name: config backup of network devices
  hosts: all
  gather_facts: no
  tasks:
  - name: get timestamp
    shell: "date +%Y%m%d-%H-%M-%S"
    register: timestamp

  - name: backup ios config
    ios_command:
            backup: yes
            backup_options:
                    filename: "running-config-{{ timestamp.stdout }}"
                    dir_path: "data/{{ inventory_hostname }}"
